language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=thumbv6m-none-eabi
      rust: beta

    - env: TARGET=thumbv7m-none-eabi
      rust: beta

    - env: TARGET=thumbv7em-none-eabi
      rust: beta

    - env: TARGET=thumbv7em-none-eabihf
      rust: beta

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
