[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "mfrc522"
version = "0.1.0"

[dependencies.embedded-hal]
git = "https://github.com/japaric/embedded-hal"

[dev-dependencies]
spidev = "0.3.0"
sysfs_gpio = "0.5.1"
